export { auth, db, storage, googleProvider } from "./config";
export {
  signInWithGoogle,
  signOutUser,
  onAuthChange,
  getUserProfile,
  updateUserProfile,
  type UserRole,
  type UserProfile,
} from "./auth";
export {
  SLUGS_RESERVADOS,
  criarPerfilCriador,
  atualizarPerfilCriador,
  obterCriadorPorSlug,
  obterCriadorPorId,
  obterCriadorPorUserId,
  listarCriadores,
  aprovarCriador,
  suspenderCriador,
  validarSlugCriador,
  type CreatorProfile,
  type CreatorStatus,
} from "./creators";
export {
  solicitarVinculoCriadorEstabelecimento,
  aprovarVinculoCriadorEstabelecimento,
  aprovarSolicitacaoDeParceriaPeloCriador,
  rejeitarVinculoCriadorEstabelecimento,
  rejeitarSolicitacaoDeParceriaPeloCriador,
  removerVinculoCriadorEstabelecimento,
  atualizarCuradoriaCriadorEstabelecimento,
  listarEstabelecimentosDoCriador,
  listarEstabelecimentosAtivosDoCriador,
  listarVinculosCriadorEstabelecimento,
  listarVinculosDetalhadosCriadorEstabelecimento,
  listarCriadoresDoEstabelecimento,
  listarCriadoresAtivosDoEstabelecimento,
  type CreatorEstablishmentLink,
  type CreatorApprovalStatus,
  type CreatorEstablishmentStatus,
  type CreatorLinkWithCreator,
  type CreatorLinkWithEstablishment,
} from "./creator-establishments";
export {
  criarEstabelecimento,
  criarEstabelecimentoPeloCriador,
  aprovarEstabelecimento,
  rejeitarOuSuspenderEstabelecimento,
  listarEstabelecimentos,
  onEstabelecimentosChange,
  criarCupom,
  alternarStatusCupom,
  listarCupons,
  resgatarCupom,
  validarResgate,
  listarResgatesDoUsuario,
  listarResgatesDoEstabelecimento,
  uploadLogoEstabelecimento,
  type Estabelecimento,
  type Cupom,
  type Resgate,
} from "./estabelecimentos";
export {
  obterCategoriasDb,
  salvarCategoriaDb,
  excluirCategoriaDb,
  inicializarCategoriasPadrao,
  type CategoryDb,
} from "./categorias";

